version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: .
    container_name: backend_container
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
      NODE_ENV: development 
    ports:
      - "3000:3000"
    command: >
      sh -c "until pg_isready -h db -U user; do
      echo 'Aguardando o PostgreSQL...'; sleep 2;
      done;
      npx prisma migrate deploy && node dist/api/server.js"